# .gitlab-ci.yml

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_TAG: latest
  DOCKER_REGISTRY_URL: registry.gitlab.com
  DOCKER_REPO_PATH: $DOCKER_REGISTRY_URL/jellyfisharuka/weatherInfo

build:
  stage: build
  script:
    - docker build -t $DOCKER_REPO_PATH:$DOCKER_IMAGE_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $DOCKER_REGISTRY_URL
    - docker push $DOCKER_REPO_PATH:$DOCKER_IMAGE_TAG
  only:
    - master

deploy:
  stage: deploy
  script:
    - echo "Deploying your application..."
    # Add your deployment commands here
  only:
    - master
